name: heylocal

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # GitHub-hosted Runner
             # windows-latest
             # macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 #코드를 runner로 가져옴

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' #JDK 설치

      - name: Restore firebase-adminsdk.json
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.HEYLOCAL_APP_PRIVATE_KEY }}" | base64 --decode > src/main/resources/firebase-adminsdk.json

      - name: Restore key file
        run: |
          echo "${{ secrets.MTLS_KEY }}" | base64 --decode > src/main/resources/heylocal-key_private.key

      - name: Restore crt file
        run: |
          echo "${{ secrets.MTLS_CRT }}" | base64 --decode > src/main/resources/heylocal-key_public.crt

      - name: Set base64 encoding key in application properties
        run: |
          echo -e "\nbase64.encoded.aes.key=${{ secrets.HEYLOCAL_USERINFO_DECRYPT_KEY }}" >> src/main/resources/application.properties

      - name: Set supabase api key in application properties
        run: |
          echo -e "\nsupabase.api.key=${{ secrets.SUPABASE_API_KEY }}" >> src/main/resources/application.properties
        
      - name: Build with Gradle
        env:
          DECRYPTION_KEY: ${{ secrets.HEYLOCAL_USERINFO_DECRYPT_KEY }}
        run: ./gradlew clean build -x test
        # 실제 빌드 수행
        
      - name: Change filename
        run: mv ./build/libs/heylocal-server-0.0.1-SNAPSHOT.jar ./heylocal.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HEYLOCAL_DEV_HOST }}
          username: ${{ secrets.HEYLOCAL_DEV_USERNAME }}
          key: ${{ secrets.HEYLOCAL_DEV_PRIVATEKEY }}
          port: 22
          source: heylocal.jar
          target: /opt/app/

      - name: Deploy and Restart App on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HEYLOCAL_DEV_HOST }}
          username: ${{ secrets.HEYLOCAL_DEV_USERNAME }}
          key: ${{ secrets.HEYLOCAL_DEV_PRIVATEKEY }}
          script: |
            echo "=== Deploying heylocal.jar ==="
            sudo systemctl stop heylocal || true
            sudo nohup java -jar /opt/app/heylocal.jar > /opt/app/app.log 2>&1 &
            echo "=== heylocal service restarted ==="
